In [175]:
#BTP Project

import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [176]:
df = pd.read_csv("BTP_Data.csv")

In [177]:
df

pH         Do       CER         WCW
0   4.959698  82.490541  0.000358    1.143750
1   4.959698  82.490541  0.000300    3.106250
2   4.959681  82.478611  0.000250    6.437500
3   4.959681  82.478611  0.000217   17.687500
4   4.959681  82.478611  0.000183   44.500000
..       ...        ...       ...         ...
60  4.961429  82.382076 -0.000367  522.410648
61  4.961017  82.290531 -0.000367  415.171978
62  4.961695  82.121197 -0.000367  300.572439
63  4.964506  82.018272 -0.000367  178.440256
64  4.965976  81.888108 -0.000367   48.603652

[65 rows x 4 columns]

In [5]:
from sklearn import linear_model

In [6]:
X = df[['pH','Do','CER']]
Y = df[['WCW']]

In [70]:
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [71]:
predictions = lm.predict(X_test)
print(predictions)

[[ 197.80693106]
 [ 869.32262812]
 [ 929.65777965]
 [1228.96019277]
 [1096.56069628]
 [1138.25313472]
 [ -96.54976089]
 [ 266.81470203]
 [ 607.77349334]
 [ 589.37626908]]


In [72]:
r2_lr = r2_score(y_test, predictions)
print('The rsquared value is: ' + str(r2_lr))

The rsquared value is: 0.8990050475658294


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.15)

In [36]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

C:\Users\Yash Chapalgaonkar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
y_pred = regressor.predict(X_test)

In [38]:
y_pred

array([  86.25      ,  935.825     ,  753.4       , 1350.34823239,
       1218.41183664, 1064.44179906,   28.4125    ,  163.04375   ,
        385.        ,  385.        ])

In [39]:
from sklearn.metrics import r2_score

In [40]:
r2 = r2_score(y_test, y_pred)
print('The rsquared value is: ' + str(r2))

The rsquared value is: 0.9692166147859016


In [41]:
y_test

WCW
6    187.250000
26  1114.250000
20   712.500000
46  1347.055739
48  1297.653639
53  1081.406264
2      6.437500
7    243.500000
13   467.000000
12   437.500000

In [57]:
from sklearn.tree import DecisionTreeRegressor 

In [58]:
regressor_dt = DecisionTreeRegressor(random_state = 0) 
regressor_dt.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [59]:
y_pred_dt = regressor_dt.predict(X_test)
y_pred_dt

array([  96.6875    ,  922.25      ,  747.5       , 1359.71692133,
       1265.346816  , 1055.67019983,   17.6875    ,   96.6875    ,
        350.        ,  350.        ])

In [60]:
r2_dt = r2_score(y_test, y_pred_dt)
print('The rsquared value is: ' + str(r2_dt))

The rsquared value is: 0.9579322229349233


In [61]:
y_pred_dt_test = regressor_dt.predict(Xf)
y_pred_dt_test

array([758.58585395, 758.58585395, 758.58585395, 758.58585395,
       758.58585395, 758.58585395, 758.58585395, 758.58585395,
       758.58585395, 758.58585395, 758.58585395, 758.58585395,
       758.58585395, 758.58585395, 758.58585395, 758.58585395,
       758.58585395, 758.58585395, 758.58585395, 758.58585395,
       758.58585395, 758.58585395, 758.58585395])

In [63]:
X_test

pH         Do       CER
6   4.959681  82.478611  0.000117
26  4.960403  82.439650 -0.000258
20  4.959646  82.441919 -0.000225
46  4.959440  82.425698 -0.000350
48  4.960093  82.425698 -0.000342
53  4.960093  82.408348 -0.000367
2   4.959681  82.478611  0.000250
7   4.959918  82.478611  0.000067
13  4.959918  82.443926 -0.000100
12  4.959918  82.443926 -0.000092

In [69]:
from sklearnarn import metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) # or mse**(0.5)  
r2_rf1 = metrics.r2_score(y_test, y_pred)

print("Results of sklearn.metrics:")
print("MAE:",mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-Squared:", r2)
 

Results of sklearn.metrics:
MAE: 65.675501069
MSE: 6672.354623837791
RMSE: 81.68448214831132
R-Squared: 0.9692166147859016


In [73]:
mae_dt = metrics.mean_absolute_error(y_test, y_pred_dt)
mse_dt = metrics.mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt) # or mse**(0.5)  
r2_dt_1 = metrics.r2_score(y_test, y_pred_dt)

print("Results of sklearn.metrics:")
print("MAE:",mae_dt)
print("MSE:", mse_dt)
print("RMSE:", rmse_dt)
print("R-Squared:", r2_dt_1)

Results of sklearn.metrics:
MAE: 75.08290695083333
MSE: 9118.267041215096
RMSE: 95.48961745244922
R-Squared: 0.9579322229349233


In [74]:
mae_lm = metrics.mean_absolute_error(y_test, predictions)
mse_lm = metrics.mean_squared_error(y_test, predictions)
rmse_lm = np.sqrt(mse_lm) # or mse**(0.5)  
r2_lm_1 = metrics.r2_score(y_test, predictions)

print("Results of sklearn.metrics:")
print("MAE:",mae_lm)
print("MSE:", mse_lm)
print("RMSE:", rmse_lm)
print("R-Squared:", r2_lm_1)

Results of sklearn.metrics:
MAE: 126.7629167587138
MSE: 21890.839268378735
RMSE: 147.95553138824764
R-Squared: 0.8990050475658294


In [116]:
Y_pred_rf = regressor.predict(X_test)
Y_pred_rf

array([  86.25      ,  935.825     ,  753.4       , 1350.34823239,
       1218.41183664, 1064.44179906,   28.4125    ,  163.04375   ,
        385.        ,  385.        ])

In [117]:
y_test

WCW
6    187.250000
26  1114.250000
20   712.500000
46  1347.055739
48  1297.653639
53  1081.406264
2      6.437500
7    243.500000
13   467.000000
12   437.500000

In [118]:
Y_pred_rf_df = pd.DataFrame(Y_pred_rf)
Y_pred_rf_df

0
0    86.250000
1   935.825000
2   753.400000
3  1350.348232
4  1218.411837
5  1064.441799
6    28.412500
7   163.043750
8   385.000000
9   385.000000

In [124]:
Y_pred_lm = lm.predict(X_test)
Y_pred_lm_df = pd.DataFrame(Y_pred_lm)
Y_pred_lm_df

0
0   197.806931
1   869.322628
2   929.657780
3  1228.960193
4  1096.560696
5  1138.253135
6   -96.549761
7   266.814702
8   607.773493
9   589.376269

In [125]:
Y_pred_dt = regressor_dt.predict(X_test)
Y_pred_dt_df = pd.DataFrame(Y_pred_dt)
Y_pred_dt_df

0
0    96.687500
1   922.250000
2   747.500000
3  1359.716921
4  1265.346816
5  1055.670200
6    17.687500
7    96.687500
8   350.000000
9   350.000000